export const union = {
  welcome: '/welcome',
  auth: '/auth',
  login: '/auth/login',
  signup: '/auth/signup',
  lightLogo: '../../../../assets/img/light-logo.png',
  darkLogo: '../../../../assets/img/logo.png',
  lightBgColor: '#c2cdee',
  darkBgColor: '#00093c',
  lightColor: '#fff',
  darkColor: '#000',
  darkSv: '../../../../assets/img/githubSv2 1.png',
  darkIv: '../../../../assets/img/githubIv2 1.png',
  darkUl: '../../../../assets/img/githubUl2 1.png',
  darkRS: '../../../../assets/img/logoRSdark 1.png',
  lightSv: '../../../../assets/img/githubSv.png',
  lightIv: '../../../../assets/img/githubIv.png',
  lightUl: '../../../../assets/img/githubUl.png',
  lightRs: '../../../../assets/img/rs-school.png',
};
